INSERT INTO Pays (nom) VALUES
('Afghanistan'),
('Albanie'),
('Algérie'),
('Andorre'),
('Angola'),
('Antigua-et-Barbuda'),
('Arabie Saoudite'),
('Argentine'),
('Arménie'),
('Australie'),
('Autriche'),
('Azerbaïdjan'),
('Bahamas'),
('Bahreïn'),
('Bangladesh'),
('Barbade'),
('Belgique'),
('Belize'),
('Bénin'),
('Bhoutan'),
('Biélorussie'),
('Birmanie'),
('Bolivie'),
('Bosnie-Herzégovine'),
('Botswana'),
('Brésil'),
('Brunei'),
('Bulgarie'),
('Burkina Faso'),
('Burundi'),
('Cambodge'),
('Cameroun'),
('Canada'),
('Cap-Vert'),
('République centrafricaine'),
('Tchad'),
('Chili'),
('Chine'),
('Colombie'),
('Comores'),
('Congo-Brazzaville'),
('Congo-Kinshasa'),
('Costa Rica'),
('Croatie'),
('Cuba'),
('Chypre'),
('République tchèque'),
('Danemark'),
('Djibouti'),
('Dominique'),
('République dominicaine'),
('Timor oriental'),
('Équateur'),
('Égypte'),
('El Salvador'),
('Guinée équatoriale'),
('Érythrée'),
('Estonie'),
('Eswatini'),
('Éthiopie'),
('Fidji'),
('Finlande'),
('France'),
('Gabon'),
('Gambie'),
('Géorgie'),
('Allemagne'),
('Ghana'),
('Grèce'),
('Grenade'),
('Guatemala'),
('Guinée'),
('Guinée-Bissau'),
('Guyana'),
('Haïti'),
('Honduras'),
('Hongrie'),
('Islande'),
('Inde'),
('Indonésie'),
('Iran'),
('Irak'),
('Irlande'),
('Israël'),
('Italie'),
('Jamaïque'),
('Japon'),
('Jordanie'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Corée du Nord'),
('Corée du Sud'),
('Kosovo'),
('Koweït'),
('Kirghizistan'),
('Laos'),
('Lettonie'),
('Liban'),
('Lesotho'),
('Liberia'),
('Libye'),
('Liechtenstein'),
('Lituanie'),
('Luxembourg'),
('Madagascar'),
('Malawi'),
('Malaisie'),
('Maldives'),
('Mali'),
('Malte'),
('Îles Marshall'),
('Mauritanie'),
('Maurice'),
('Mexique'),
('Micronésie'),
('Moldavie'),
('Monaco'),
('Mongolie'),
('Monténégro'),
('Maroc'),
('Mozambique'),
('Namibie'),
('Nauru'),
('Népal'),
('Pays-Bas'),
('Nouvelle-Zélande'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Macédoine du Nord'),
('Norvège'),
('Oman'),
('Pakistan'),
('Palaos'),
('Palestine'),
('Panama'),
('Papouasie-Nouvelle-Guinée'),
('Paraguay'),
('Pérou'),
('Philippines'),
('Pologne'),
('Portugal'),
('Qatar'),
('Roumanie'),
('Russie'),
('Rwanda'),
('Saint-Christophe-et-Niévès'),
('Sainte-Lucie'),
('Saint-Vincent-et-les-Grenadines'),
('Samoa'),
('Saint-Marin'),
('Sao Tomé-et-Principe'),
('Arabie Saoudite'),
('Sénégal'),
('Serbie'),
('Seychelles'),
('Sierra Leone'),
('Singapour'),
('Slovaquie'),
('Slovénie'),
('Îles Salomon'),
('Somalie'),
('Afrique du Sud'),
('Soudan du Sud'),
('Espagne'),
('Sri Lanka'),
('Soudan'),
('Suriname'),
('Suède'),
('Suisse'),
('Syrie'),
('Taïwan'),
('Tadjikistan'),
('Tanzanie'),
('Thaïlande'),
('Togo'),
('Tonga'),
('Trinité-et-Tobago'),
('Tunisie'),
('Turquie'),
('Turkménistan'),
('Tuvalu'),
('Ouganda'),
('Ukraine'),
('Émirats arabes unis'),
('Royaume-Uni'),
('États-Unis'),
('Uruguay'),
('Ouzbékistan'),
('Vanuatu'),
('Vatican'),
('Venezuela'),
('Vietnam'),
('Yémen'),
('Zambie'),
('Zimbabwe');
